catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('onloan/', views.AllLoanedBooksListView.as_view(), name="all-borrowed"),
]

urlpatterns += [
    path('addstaff/', views.staff_add_view, name="addStaff"),
    path('logs/', views.LogListView.as_view(), name='logs')
]

urlpatterns += [
    path('borrowed/<uuid:pk>/', views.borrowBook_view, name='borrowBook'),
    path('review/<int:pk>', views.reviewCreate_view, name='commentReview'),
    path('returned/<uuid:pk>/', views.returnBook_view, name='returnBook'),
]

urlpatterns += [
    path('author/modifyauthors/', views.AuthorsModify.as_view(), name='author_modify'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
    path('book/modifybooks/', views.BooksModify.as_view(), name='book_modify'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

urlpatterns+=[
    path('bookinstance/modifybooks/', views.BookInstanceModify.as_view(), name='bookinstance_modify'),
    path('bookinstance/create/', views.BookInstanceCreate.as_view(), name ='book_instance_create'),
    path('bookinstance/<uuid:pk>/update/', views.BookInstanceUpdate.as_view(), name ='book_instance_update'),
    path('bookinstance/<uuid:pk>/delete/', views.BookInstanceDelete.as_view(), name ='book_instance_delete'),
]

urlpatterns+=[
    path('language/modifybooks/', views.LanguageModify.as_view(), name='language_modify'),
    path('language/create/', views.LanguageCreate.as_view(), name ='language_create'),
    path('language/<int:pk>/update/', views.LanguageUpdate.as_view(), name ='language_update'),
    path('language/<int:pk>/delete/', views.LanguageDelete.as_view(), name ='language_delete'),
]

urlpatterns+=[
    path('genre/modifybooks/', views.GenreModify.as_view(), name='genre_modify'), 
    path('genre/create/', views.GenreCreate.as_view(), name ='genre_create'),
    path('genre/<int:pk>/update/', views.GenreUpdate.as_view(), name ='genre_update'),
    path('genre/<int:pk>/delete/', views.GenreDelete.as_view(), name ='genre_delete'),
]

urlpatterns += [
    path('profile/', views.UserProfile.as_view(), name='user_profile'),
]

urlpatterns += [
    path('signup/', views.signup_view, name="signup"),
    path('lockout/', views.lockout_view, name="lockout"),
    path('passwordreset/', views.passwordReset_view, name="reset"),
    path('emailreset/', views.emailRequest_view, name="email-reset"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
from django.urls import path

urlpatterns += [
    path('catalog/', include('catalog.urls'), name="catalog"),
]

from django.views.generic import RedirectView

urlpatterns += [
    path('',RedirectView.as_view(url='catalog/',permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

handler404 = 'catalog.views.error_404'
handler403 = 'catalog.views.error_403'

urlpatterns += [
    path('session_security/', include('session_security.urls')),
]

from catalog.views import signup_view, lockout_view
from catalog.views import passwordReset_view
from catalog.views import emailRequest_view
from catalog.views import changePassword_view
urlpatterns += [
    path('signup/', signup_view, name="signup"),
    path('accounts/login/lockout/', lockout_view, name="lockout"),
    path('emailreset/', emailRequest_view, name="email-request"),
    path('passwordreset/', passwordReset_view, name='reset'),
    path('passwordchange/', changePassword_view, name='change-password'),
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
import datetime
from django.urls import reverse
import uuid
from django.core.validators import MaxValueValidator, MinValueValidator

class Genre(models.Model):
    name = models.CharField(max_length=200,help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name
        
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character ISBN number')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    publisher = models.CharField(max_length=50, null=True)
    date_added_to_library = models.DateField(null=True, blank=True)
    year = models.IntegerField(validators=[MaxValueValidator(datetime.date.today().year), MinValueValidator(1900)], null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title  

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])  


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    returnedBooks = models.ForeignKey('ReturnedBooks', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_added = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('a','Available'),
        ('r','Reserved'),
    )
	
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


    def get_absolute_url(self):
        return reverse('book instance-detail', args=[str(self.id)]) 

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    @property
    def is_available(self):
        if self.due_back == None:
            return True
        return False

class Author(models.Model):
    """Model representing an author."""
    given_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died',null=True,blank=True)

    class Meta:
        ordering = ['given_name', 'last_name']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.given_name}'     

class Language(models.Model):
    """Model representing a language"""
    language = models.CharField(max_length=100)

    class Meta:
        ordering = ['language']

    def __str__(self):
        """String for representing the Model object."""
        return self.language

class Review(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID')
    book =  models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    user =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    review =  models.TextField(max_length=1000, help_text='Enter a brief review of the book')
    rating =  models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(1)], help_text='1 - Lowest, 10 - Highest')

    def __str__(self):
        """String for representing the Model object."""
        return self.review  

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('review-details', args=[str(self.id)])  

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=100, blank=True)
    idno = models.CharField(max_length=8)

    QUESTION_SAMPLES = (
        ('1', 'In what city did you have your first ever birthday party?'),
        ('2', 'What is the last name of your Science class teacher in high school?'),
        ('3', 'Which company manufactured your first mobile phone?'),
        ('4', 'Who was your childhood hero?'),
        ('5', 'Where was your best family vacation?')
    )

    question = models.CharField(
        max_length=1,
        choices=QUESTION_SAMPLES,
        blank=True,
        default='m',
        help_text='Security Question',
    )

    answer =  models.CharField(max_length=30, blank=True)

    class Meta:
        permissions = (("can_add_staff", "Add Staff Profile"),)

    def __str__(self):
        return self.user.username
    
class ReturnedBooks(models.Model):
    user =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    return_date = models.DateField(null=True, blank=True)
    book =  models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.user.username
    

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

    instance.profile.save()

class Log (models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID')
    user =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    action = models.TextField(max_length=1000, help_text='Action')
    item = models.CharField(max_length = 300)
    timestamp = models.DateTimeField()

    def __str__(self):
        return self.action

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from catalog.models import Profile, Review
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    
    QUESTION_SAMPLES = (
        ('1', 'In what city did you have your first ever birthday party?'),
        ('2', 'What is the last name of your Science class teacher in high school?'),
        ('3', 'Which company manufactured your first mobile phone?'),
        ('4', 'Who was your childhood hero?'),
        ('5', 'Where was your best family vacation?')
    )

    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=100)
    idno = forms.CharField(max_length=8)
    question = forms.CharField(widget=forms.Select(choices = QUESTION_SAMPLES))
    answer = forms.CharField(max_length=30)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            match = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('Email is already in use.')
    
    class Meta():   
        model = User
        fields = ('username','first_name','last_name','idno','email','password1','password2','question','answer')


class QuestionForm(forms.Form):
    answer = forms.CharField(max_length=100, help_text="Enter answer to question.", widget=forms.TextInput(attrs={'autocomplete':'off'}))
    def clean_answer(self):
        answer1 = self.cleaned_data['answer']

        return answer1

    class Meta():
        fields = ('answer')


class EmailForm(forms.Form):
    email = forms.EmailField(max_length=100, help_text="Enter Email Address", widget=forms.TextInput(attrs={'autocomplete':'off'}))

    class Meta():
        fields = ('email')

from django.contrib.auth.forms import SetPasswordForm
class PasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label=_("New Password"), widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=_("New Password Confirmation"), widget=forms.PasswordInput)

    class Meta():
        fields = ('new_password1', 'new_password2')

class borrowForm (forms.Form):
    comm_borrow = forms.CharField()

class returnForm (forms.Form):
    comm_return = forms.CharField()

class commentForm (forms.ModelForm):
    class Meta():
        model = Review
        fields = ('rating', 'review')

class returnForm (forms.Form):
    comm_return = forms.CharField()

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
<div id="centerSignUp">
    <h1 id="signUpTitle">Modify Author</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div>
                        <div id="signUpLabels">{{ form.given_name.label_tag }}</div>
                        {{ form.given_name }}
                        {{ form.given_name.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.last_name.label_tag }}</div>
                        {{ form.last_name }}
                        {{ form.last_name.errors }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div>
                        <div id="signUpLabels">{{ form.date_of_birth.label_tag }}</div>
                        {{ form.date_of_birth }}
                        {{ form.date_of_birth.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.date_of_death.label_tag }}</div>
                        {{ form.date_of_death }}
                        {{ form.date_of_death.errors }}
                    </div>
                </div>
            </div>
        </div>
        <input onmouseover="changeLoginButton()" onmouseout="resetLoginButton()" type="submit" value="Submit" id="loginSubmit">
        <a onmouseover="changeSignUpBackButton()" onmouseout="resetSignUpBackButton()" href="{% url 'author_modify' %}" id="signUpBack">Cancel</a>
    </form>
</div>
    
{% endblock %}

{% block title %}
    <title>Nowledge | Modify Author</title>
{% endblock %}

catalog/templates/catalog/book_detail.html
    {% extends "base_generic.html" %}

    {% block content %}
    <br>
    <h1 style="margin: 0; display: inline-block"id="signUpTitle">{{ book.title }}</h1>
    {% if perms.catalog.can_mark_returned %}
    <a onmouseover="changeSignUpBackButton()" onmouseout="resetSignUpBackButton()" href="{% url 'book_modify' %}" id="signUpBack">Back</a>
    {% else %}
    <a onmouseover="changeSignUpBackButton()" onmouseout="resetSignUpBackButton()" href="{% url 'books' %}" id="signUpBack">Back</a>
    {% endif %}

    <hr>

    <ul id="profileInfoList">
        <li>
            <h5><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></h5>
            <h5><strong>Genre:</strong> {{ book.genre.all|join:", " }}</h5>
        </li>
        <li>
            <h5><strong>Language:</strong> {{ book.language }}</h5>
            <h5><strong>ISBN:</strong> {{ book.isbn }}</h5>
        </li>
        <li>
            <h5><strong>Year:</strong> {{ book.year }}</h5>
            <h5><strong>Imprint: </strong>{{book.publisher}}</h5>
            <br>
        </li>
        <li>
            <br>
        </li>
    </ul>
    <h5 id="detailSummary"><strong>Summary:</strong> {{ book.summary }}</h5>

    <div id="detailCopies">

        <hr>
        {% if user.is_authenticated %}
        <h3>Copies</h3>
        <br>
        {% for copy in book.bookinstance_set.all %}
        <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'r' %}text-danger{% else %}text-warning{% endif %}">
            <strong>Status:</strong> {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
        <p><strong>Due to be returned: </strong> {{ copy.due_back }}</p>
        {% if perms.catalog.can_mark_returned %}
        <p><strong>Borrower: </strong> {{ copy.borrower.username }}</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" formaction="{% url 'returnBook' copy.pk %}" id="loginSubmit">Return Book</button>
            </form>
            <br>
        {% endif %}
        {% elif copy.status == 'a' and not perms.catalog.can_mark_returned %}
        <form method="post">
            {% csrf_token %}
            <button type="submit" formaction="{% url 'borrowBook' copy.pk %}" id="loginSubmit">Borrow Book</button>
        </form>
        <br>
        {% endif %}
        
        
        <hr>
        {% endfor %}
        {% endif %}



        
        <h3>Reviews</h3>
        {% if user.is_authenticated and not perms.catalog.can_mark_returned%}
        <form method = "post">
            {% csrf_token %}
            <button onmouseover="changeLoginButton()" onmouseout="resetLoginButton()" type="submit" formaction="{% url 'commentReview' book.pk %}" id="loginSubmit">Add Review</button>

        </form>
        {% endif %}

        {% for review_set in book.review_set.all %}
        <hr>
        <p><strong>User: </strong>{{review_set.user}}</p>
        <p><strong>Rating: </strong>{{review_set.rating}}</p>
        <p><strong>Review: </strong>{{review_set.review}}</p>
        {% endfor %}
        <hr>
        
       
    </div>
    {% endblock %}

    {% block title %}
    <title>Nowledge | Book Details</title>
    {% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
<div id="centerSignUp">
    <h1 id="signUpTitle">Modify Book</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div>
                        <div id="signUpLabels">{{ form.title.label_tag }}</div>
                        {{ form.title }}
                        {{ form.title.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.author.label_tag }}</div>
                        {{ form.author }}
                        {{ form.author.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.genre.label_tag }}</div>
                        {{ form.genre }}
                        {{ form.genre.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.year.label_tag }}</div>
                        {{ form.year }}
                        {{ form.year.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.summary.label_tag }}</div>
                        {{ form.summary }}
                        {{ form.summary.errors }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div>
                        <div id="signUpLabels">{{ form.language.label_tag }}</div>
                        {{ form.language }}
                        {{ form.language.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.publisher.label_tag }}</div>
                        {{ form.publisher }}
                        {{ form.publisher.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.isbn.label_tag }}</div>
                        {{ form.isbn }}
                        {{ form.isbn.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.date_added_to_library.label_tag }}</div>
                        {{ form.date_added_to_library }}
                        {{ form.date_added_to_library.errors }}
                    </div>
                </div>
            </div>
        </div>
        <input onmouseover="changeLoginButton()" onmouseout="resetLoginButton()" type="submit" value="Submit" id="loginSubmit">
        <a onmouseover="changeSignUpBackButton()" onmouseout="resetSignUpBackButton()" href="{% url 'book_modify' %}" id="signUpBack">Cancel</a>
    </form>
</div>
    
{% endblock %}

{% block title %}
    <title>Nowledge | Modify Book</title>
{% endblock %}

catalog/templates/catalog/book_modify.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 id="modifyTitle">Modify Books</h1>
  <a onmouseover="changeModifyAddButton()" onmouseout="resetModifyAddButton()" id="modifyAddButton" href="{% url 'book_create' %}">Add Book</a>
  {% if book_list %}
  <table id="modifyTable">
    <tr>
      <th>Book Title</td>
      <th>Author</td>
    </tr>
    {% for book in book_list %}
    <tr>
      <td id="modifyCol1"><a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a></td>    
      <td id="modifyCol2">{{book.author}}</td>
      <td><a id="modifyUpdate" href="{% url 'book_update' book.pk %}">Update</a></td>
      <td><a id="modifyDelete" href="{% url 'book_delete' book.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
  </table>
    
  {% else %}
  <br>
  <br>
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

{% block title %}
    <title>Nowledge | Modify Book</title>
{% endblock %}

catalog/templates/catalog/bookinstance_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div id="center">
    <h1>Delete Book Instance</h1>
    <br>
    <p>Are you sure you want to delete the Book Instance: <br><br> <strong> {{ bookinstance.book.title }}</strong></p>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        <input onmouseover="changeLoginButton()" onmouseout="resetLoginButton()" type="submit" value="Yes - Delete" id="loginSubmit">
        <a onmouseover="changeSignUpBackButton()" onmouseout="resetSignUpBackButton()" href="{% url 'bookinstance_modify' %}" id="signUpBack">Cancel</a>
    </form>
</div>
{% endblock %}

{% block title %}
    <title>Nowledge | Delete Book Instance</title>
{% endblock %}

catalog/templates/catalog/bookinstance_form.html
{% extends "base_generic.html" %}

{% block content %}
<div id="centerSignUp">
    <h1 id="signUpTitle">Modify Book Instance</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div>
                        <div id="signUpLabels">{{ form.book.label_tag }}</div>
                        {{ form.book }}
                        {{ form.book.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.borrower.label_tag }}</div>
                        {{ form.borrower }}
                        {{ form.borrower.errors }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div>
                        <div id="signUpLabels">{{ form.due_back.label_tag }}</div>
                        {{ form.due_back }}
                        {{ form.due_back.errors }}
                    </div>
                    <div>
                        <div id="signUpLabels">{{ form.date_added.label_tag }}</div>
                        {{ form.date_added }}
                        {{ form.date_added.errors }}
                    </div>
                </div>
            </div>
        </div>
        <input onmouseover="changeLoginButton()" onmouseout="resetLoginButton()" type="submit" value="Submit" id="loginSubmit">
        <a onmouseover="changeSignUpBackButton()" onmouseout="resetSignUpBackButton()" href="{% url 'bookinstance_modify' %}" id="signUpBack">Cancel</a>
    </form>
</div>
    
{% endblock %}

{% block title %}
    <title>Nowledge | Modify Book Instance</title>
{% endblock %}

catalog/templates/catalog/bookinstance_modify.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 id="modifyTitle">Modify Book Instances</h1>
  <a onmouseover="changeModifyAddButton()" onmouseout="resetModifyAddButton()" id="modifyAddButton" href="{% url 'book_instance_create' %}">Add Book Instance</a>
  {% if bookinstance_list %}
  <table id="modifyTable">
    <tr>
      <th>Book Title</td>
    </tr>
    {% for bookinstance in bookinstance_list %}
    <tr>
      <td id="modifyCol1"><a href="{% url 'book-detail' bookinstance.book.pk %}">{{ bookinstance.book.title }}</a></td>    
      <td><a id="modifyUpdate" href="{% url 'book_instance_update' bookinstance.pk %}">Update</a></td>
      <td><a id="modifyDelete" href="{% url 'book_instance_delete' bookinstance.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
  </table>
    
  {% else %}
  <br>
  <br>
    <p>There are no book instances in the library.</p>
  {% endif %}       
{% endblock %}

{% block title %}
    <title>Nowledge | Modify Book Instance</title>
{% endblock %}

catalog/templates/catalog/genre_modify.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 id="modifyTitle">Modify Genres</h1>
  <a onmouseover="changeModifyAddButton()" onmouseout="resetModifyAddButton()" id="modifyAddButton" href="{% url 'genre_create' %}">Add Genre</a>
  {% if genre_list %}
  <table id="modifyTable">
    <tr>
      <th>Genre</td>
    </tr>
    {% for genre in genre_list %}
    <tr>
      <td id="modifyCol1">{{ genre.name }}</td>    
      <td><a id="modifyUpdate" href="{% url 'genre_update' genre.pk %}">Update</a></td>
      <td><a id="modifyDelete" href="{% url 'genre_delete' genre.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
  </table>
    
  {% else %}
  <br>
  <br>
    <p>There are no genres in the library.</p>
  {% endif %}       
{% endblock %}

{% block title %}
    <title>Nowledge | Modify Genre</title>
{% endblock %}

catalog/templates/catalog/language_modify.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 id="modifyTitle">Modify Languages</h1>
  <a onmouseover="changeModifyAddButton()" onmouseout="resetModifyAddButton()" id="modifyAddButton" href="{% url 'language_create' %}">Add Language</a>
  {% if language_list %}
  <table id="modifyTable">
    <tr>
      <th>Language</td>
    </tr>
    {% for language in language_list %}
    <tr>
      <td id="modifyCol1">{{ language.language }}</td>    
      <td><a id="modifyUpdate" href="{% url 'language_update' language.pk %}">Update</a></td>
      <td><a id="modifyDelete" href="{% url 'language_delete' language.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
  </table>
    
  {% else %}
  <br>
  <br>
    <p>There are no languages in the library.</p>
  {% endif %}       
{% endblock %}

{% block title %}
    <title>Nowledge | Modify Language</title>
{% endblock %}

catalog/templates/catalog/register.html
{% extends "base_generic.html" %}

{% block content %}
    <form method="POST" class="form-group">
	{% csrf_token %}
    {{ form.username }}
    {{ form.email }}
    {{ form.password1 }}
    {{ form.password2 }}
	<button type="submit" class="btn btn-success">Register</button>
    </form>
{% endblock %}